### PR TITLE
Add Crystal port

### PR DESCRIPTION
**Pull request by EddieRingle**
...which is actually just a straight clone of the Ruby
version thanks to Crystal being heavily influenced by Ruby.

Signed-off-by: Eddie Ringle eddie@ringle.io

### CODE REVIEW

**Comment by EddieRingle** [comment]
Benchmarks compared to Ruby, GCC, and Clang:

```
ganglion:genprime eddie$ ruby --version
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
ganglion:genprime eddie$ ruby genprime.rb 250000 1000000
Found   250000 primes in    9.37871 seconds (last was    3497861)
Found   500000 primes in   26.64565 seconds (last was    7368787)
Found   750000 primes in   49.49289 seconds (last was   11381621)
Found  1000000 primes in   77.66281 seconds (last was   15485863)
```

```
ganglion:genprime eddie$ gcc --version
gcc (Homebrew gcc49 4.9.2_1) 4.9.2
ganglion:genprime eddie$ ./genprime-c 250000 1000000
Found   250000 primes in    1.58057 seconds (last was    3497861)
Found   500000 primes in    4.62826 seconds (last was    7368787)
Found   750000 primes in    8.44525 seconds (last was   11381621)
Found  1000000 primes in   13.11020 seconds (last was   15485863)

Size:
-rwxr-xr-x   1 eddie  staff    8728 May  4 11:16 genprime-c
```

```
ganglion:genprime eddie$ clang-3.6 --version
clang version 3.6.0 (tags/RELEASE_360/final)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
ganglion:genprime eddie$ ./genprime-c-clang 250000 1000000
Found   250000 primes in    1.75568 seconds (last was    3497861)
Found   500000 primes in    5.07071 seconds (last was    7368787)
Found   750000 primes in    9.87592 seconds (last was   11381621)
Found  1000000 primes in   15.81370 seconds (last was   15485863)

Size:
-rwxr-xr-x   1 eddie  staff    8720 May  4 11:19 genprime-c-clang
```

---

```
ganglion:genprime eddie$ crystal --version
Crystal 0.7.1 [86d387c] (Fri May  1 01:04:41 UTC 2015)
ganglion:genprime eddie$ ./genprime-crystal 250000 1000000
Found   250000 primes in    0.62365 seconds (last was    3497861)
Found   500000 primes in    1.76807 seconds (last was    7368787)
Found   750000 primes in    3.29689 seconds (last was   11381621)
Found  1000000 primes in    5.02163 seconds (last was   15485863)

Size:
-rwxr-xr-x   1 eddie  staff  330540 May  4 11:06 genprime-crystal
```

**Comment by tycho** [comment]
I haven't heard of Crystal. Can you post more info about it?

**Comment by tycho** [comment]
Whoah, that's a big binary:

$ ls -cahl genprime-c{,rystal}
-rwxr-xr-x 1 snoonan snoonan 9.1K May  4 09:59 genprime-c
-rwxr-xr-x 1 snoonan snoonan 519K May  4 09:59 genprime-crystal

**Comment by EddieRingle** [comment]
http://crystal-lang.org/
https://github.com/manastech/crystal

Yeah, the binary is pretty big, but it's fast and the language is still pre-1.0 so I'm not really sure I mind it so much right now.

**Comment by EddieRingle** [comment]
They don't intend for you to be able to compile a Ruby program directly, FYI. It just happened to work out of the box in this case.

**Comment by tycho** [comment]
I was wondering why the Crystal version was faster than the C version... I figured it out. It turns out Crystal is using 32-bit integers while the C version is using 'unsigned long' (which is 64-bit on x86_64 and 32-bit on x86_32).

If I force the C version to use 32-bit integers the performance difference disappears:

```
$ git diff
diff --git a/genprime.c b/genprime.c
index 914d423..4690e46 100644
--- a/genprime.c
+++ b/genprime.c
@@ -3,7 +3,7 @@
 #include <stdlib.h>
 #include <sys/time.h>
 
-typedef unsigned long prime_t;
+typedef unsigned int prime_t;
 typedef int BOOL;
 #define TRUE -1
 #define FALSE 0

$ make genprime-c genprime-crystal
gcc -O3 -pipe -ansi -pedantic -Wall -S -o genprime-c.s genprime.c
genprime.c: In function ‘main’:
genprime.c:61:11: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 2 has type ‘prime_t {aka unsigned int}’ [-Wformat=]
   printf ("Found %8lu primes in %10.5f seconds (last was %10lu)\n",
           ^
genprime.c:61:11: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘prime_t {aka unsigned int}’ [-Wformat=]
gcc -O3 -pipe -o genprime-c genprime-c.s -lm

crystal build --release -o genprime-crystal genprime.cr

$ ./genprime-crystal 25000 250000
Found    25000 primes in    0.02249 seconds (last was     287117)
Found    50000 primes in    0.06367 seconds (last was     611953)
Found    75000 primes in    0.11751 seconds (last was     951161)
Found   100000 primes in    0.18249 seconds (last was    1299709)
Found   125000 primes in    0.26273 seconds (last was    1655131)
Found   150000 primes in    0.33856 seconds (last was    2015177)
Found   175000 primes in    0.42800 seconds (last was    2381147)
Found   200000 primes in    0.52524 seconds (last was    2750159)
Found   225000 primes in    0.62935 seconds (last was    3122321)
Found   250000 primes in    0.73814 seconds (last was    3497861)

$ ./genprime-c 25000 250000
Found    25000 primes in    0.02236 seconds (last was     287117)
Found    50000 primes in    0.06303 seconds (last was     611953)
Found    75000 primes in    0.11645 seconds (last was     951161)
Found   100000 primes in    0.18120 seconds (last was    1299709)
Found   125000 primes in    0.25449 seconds (last was    1655131)
Found   150000 primes in    0.33531 seconds (last was    2015177)
Found   175000 primes in    0.42508 seconds (last was    2381147)
Found   200000 primes in    0.52136 seconds (last was    2750159)
Found   225000 primes in    0.62455 seconds (last was    3122321)
Found   250000 primes in    0.73455 seconds (last was    3497861)
```

**Comment by EddieRingle** [comment]
Yeah, I figured there was something weird going on. Good catch.

**Pull request merged**
